export const SECTION_VARIANT_OPTIONS: Record<string, string[]> = {
  hero: [
    'centered',
    'split-photo-right',
    'split-photo-left',
    'photo-background',
    'photo-screenwide-top',
    'overlap',
    'video-background',
    'gallery-background',
    'gallery-screenwide-top',
  ],
  testimonials: ['carousel', 'grid', 'masonry', 'slider-vertical', 'featured-single'],
  howItWorks: ['horizontal', 'vertical', 'cards', 'vertical-image-right'],
  conditions: [
    'grid-cards-4x',
    'grid-cards-3x',
    'categories-tabs',
    'list-detailed',
    'icon-grid',
    'category-detail-alternating',
  ],
  services: ['grid-cards-2x', 'grid-cards-3x', 'featured-large', 'list-horizontal', 'accordion', 'tabs', 'detail-alternating', 'detail-image-right'],
  servicesList: ['grid-cards-2x', 'grid-cards-3x', 'featured-large', 'list-horizontal', 'accordion', 'tabs', 'detail-alternating', 'detail-image-right'],
  overview: ['centered', 'left'],
  blog: ['cards-grid', 'featured-side', 'list-detailed', 'carousel'],
  gallery: ['grid-masonry', 'grid-uniform', 'carousel', 'lightbox-grid'],
  cta: ['centered', 'split', 'banner', 'card-elevated'],
  profile: ['split', 'stacked'],
  credentials: ['list', 'grid'],
  specializations: ['grid-2', 'grid-3', 'list'],
  philosophy: ['cards', 'timeline'],
  journey: ['prose', 'card'],
  affiliations: ['compact', 'detailed'],
  continuingEducation: ['compact', 'detailed'],
  clinic: ['split', 'cards'],
  introduction: ['centered', 'left'],
  hours: ['grid', 'list'],
  form: ['single-column', 'two-column', 'multi-step', 'modal', 'inline-minimal'],
  map: ['shown', 'hidden'],
  faq: ['accordion', 'simple', 'card'],
  individualTreatments: ['grid-3', 'grid-2', 'list'],
  packages: ['grid-3', 'grid-2', 'list'],
  insurance: ['split', 'stacked'],
  policies: ['grid', 'list'],
  statistics: ['horizontal-row', 'grid-2x2', 'vertical-cards', 'inline-badges'],
};

export const SITE_SETTINGS_PATHS = new Set([
  'navigation.json',
  'header.json',
  'footer.json',
  'seo.json',
  'theme.json',
  'site.json',
]);
